on:
  release:
    types:
      - created


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/shunkei_sdk
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -e '.[dev]'
    - run: python -m build
    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
